[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "community-sdks-godaddy"
version = "1.0.0"
description = "Community GoDaddy SDK for Python"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["requests>=2.31.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
