[project]
name = "community-sdks-godaddy"
version = "1.0.2"
description = "Community GoDaddy SDK for Python"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name = "Sasa Orasanin" }
]
dependencies = ["requests>=2.31.0"]

keywords = ["godaddy", "sdk", "python", "domains", "api"]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/community-sdks/godaddy-py"
Repository = "https://github.com/community-sdks/godaddy-py"
Issues = "https://github.com/community-sdks/godaddy-py/issues"